### ISSUE TITLE
Just a Question Thank you 

### ISSUE THREAD

**Issue by XxHailHydraxX** [Unam3dd/sqlivuln#1]
Does it output valid Vun to a txt file ?? & If not for a noob how hard would it be for me to adjust myself ?

Sorry if i opened the issue wrong :/

**Comment by Unam3dd** [comment]
no it doesn't generate any output file the -uf option allows you to set a text file containing the links you want to try

**Comment by XxHailHydraxX** [comment]
Thank you very for the answer <3 Love the Tool its what i needed doesn't show any false positive Hits . So again thank you and thank you for this Tool !!!

**Comment by Unam3dd** [comment]
Thanks man =)
